config/routes.rb
NinetyNineCatsDay1::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect("/cats")
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  end_date   :date             not null
#  start_date :date             not null
#  status     :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequest < ActiveRecord::Base
  STATUS_STATES = %w(APPROVED DENIED PENDING)

  belongs_to :cat
  belongs_to(
    :requester,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: "User"
  )

  after_initialize :assign_pending_status

  validates(
    :cat_id,
    :end_date,
    :start_date,
    :status,
    presence: true
  )
  validates :status, inclusion: STATUS_STATES
  validate :start_must_come_before_end
  validate :does_not_overlap_approved_request

  def approve!
    raise "not pending" unless self.status == "PENDING"
    transaction do
      self.status = "APPROVED"
      self.save!

      # when we approve this request, we reject all other overlapping
      # requests for this cat.
      overlapping_pending_requests.update_all(status: 'DENIED')
    end
  end

  def approved?
    self.status == "APPROVED"
  end

  def denied?
    self.status == "DENIED"
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == "PENDING"
  end



  private
  def assign_pending_status
    self.status ||= "PENDING"
  end


  def overlapping_requests
    CatRentalRequest
      .where("(:id IS NULL) OR (id != :id)", id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
       NOT( (start_date > :end_date) OR (end_date < :start_date) )
SQL
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  def does_not_overlap_approved_request
    # A denied request doesn't need to be checked. A pending request
    # should be checked; users shouldn't be able to make requests for
    # periods during which a cat has already been spoken for.
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] <<
        "Request conflicts with existing approved request"
    end
  end

  def start_must_come_before_end
    return if start_date < end_date
    errors[:start_date] << "must come before end date"
    errors[:end_date] << "must come after start date"
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def create
    @rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages
      render :new
    end
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  def new
    @rental_request = CatRentalRequest.new
  end

  private
  def current_cat_rental_request
    @rental_request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def cat_rental_request_params
    params.require(:cat_rental_request)
      .permit(:cat_id, :end_date, :start_date, :status)
  end


end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>Create Rental Request</h1>

<%= render "shared/errors" %>

<form action="<%= cat_rental_requests_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%=form_authenticity_token%>">
  <label for="cat_rental_request_cat_id">Cat</label>
  <select name="cat_rental_request[cat_id]"
          id="cat_rental_request_cat_id">
    <option></option>
    <% Cat.all.each do |cat| %>
      <% selected = @rental_request.cat_id == cat.id %>
      <option <%= selected ? "selected" : "" %>
              value="<%= cat.id %>">
        <%= cat.name %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="cat_rental_request_start_date">Start Date</label>
  <input
    type="date"
    name="cat_rental_request[start_date]"
    value="<%= @rental_request.start_date %>"
    id="cat_rental_request_start_date">
  <br>

  <label for="cat_rental_request_end_date">End Date</label>
  <input
    type="date"
    name="cat_rental_request[end_date]"
    value="<%= @rental_request.end_date %>"
    id="cat_rental_request_end_date">
  <br>

  <input type="submit">
</form>